// Code generated by "stringer -type=ComponentStatus"; DO NOT EDIT.

package statuspage

import "strconv"

const _ComponentStatus_name = "OperationalUnderMaintenanceDegradedPerformancePartialOutageMajorOutage"

var _ComponentStatus_index = [...]uint8{0, 11, 27, 46, 59, 70}

func (i ComponentStatus) String() string {
	if i < 0 || i >= ComponentStatus(len(_ComponentStatus_index)-1) {
		return "ComponentStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentStatus_name[_ComponentStatus_index[i]:_ComponentStatus_index[i+1]]
}
